on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:

    # failed to run git: fatal: not a git repository (or any of the parent directories): .git
    #- name: Show variables before
    #  run: |
    #    gh variable list
    #  env:
    #    GH_TOKEN: ${{ secrets.PAT }}

    - name: Get Data
      id: info
      uses: Reality-Check-Inc/version-action@v1.0

    # By default, Linux runners use the bash shell,
    # so you must use the syntax $NAME.
    # By default, Windows runners use PowerShell,
    # so you would use the syntax $env:NAME
    # Use the output from the `info` step
    - name: Set the output time and version variables
      run: |
        echo "NUGET_TIME=$(echo ${{ steps.info.outputs.time }})" >> $GITHUB_ENV
        echo "NUGET_VERSION=$(echo ${{ steps.info.outputs.version }})" >> $GITHUB_ENV

    - name: Show the current output time and version.
      run: |
        echo $NUGET_TIME
        echo $NUGET_VERSION

    # failed to run git: fatal: not a git repository (or any of the parent directories): .git
    #- name: Show variables after
    #  run: |
    #      gh variable list
    #  env:
    #    GH_TOKEN: ${{ secrets.PAT }}
