on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:

    # failed to run git: fatal: not a git repository (or any of the parent directories): .git
    #- name: Show variables before
    #  run: |
    #    gh variable list
    #  env:
    #    GH_TOKEN: ${{ secrets.PAT }}

    - name: Get Data
      id: info
      uses: Reality-Check-Inc/version-action@v1.0.2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #    GH_TOKEN: ${{ secrets.PAT }}

    # By default, Linux runners use the bash shell,
    # so you must use the syntax $NAME.
    # By default, Windows runners use PowerShell,
    # so you would use the syntax $env:NAME
    # Use the output from the `info` step
    - name: Set the output time and version variables
      run: |
        echo "nug_time=${{ steps.info.outputs.time }}" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "nug_version=${{ steps.info.outputs.version }}" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Show the current output time and version.
      run: |
        echo "${{ env.nug_time }}"
        echo "${{ env.nug_version }}"

    # failed to run git: fatal: not a git repository (or any of the parent directories): .git
    #- name: Show variables after
    #  run: |
    #      gh variable list
    #  env:
    #    GH_TOKEN: ${{ secrets.PAT }}
